notifications:
  email:
    on_success: always
    on_failure: always

language: node_js

node_js:
  - '10'

addons:
  apt:
    packages:
      # cypress dep
      - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - yarn

script:
  - yarn build
  - yarn test:ci
