/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv from 'ajv';
import User from './User';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));


export const UserSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "defaultProperties": [
  ],
  "properties": {
    "avatarUrl": {
      "type": "string"
    },
    "email": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "url": {
      "type": "string"
    }
  },
  "required": [
    "avatarUrl",
    "email",
    "name",
    "url"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isUser = ajv.compile(UserSchema) as ValidateFunction<User>;
export default function validate(value: unknown): User {
  if (isUser(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isUser.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'User'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
